[header]
# Header line regex:
pattern = ^(option: |requirements: |ci: |doc: |release: |script: |format: |test: |quality: ).+$

[body]
# Require commit to have a body. (i.e. prevent single line commit message).
required = true

[footer]
# Footer line regex
pattern = ^(Signed-off-by: |Co-authored-by: |Refs: |Fixes: ).+$
