[project]
name = "commit_format"
version = "0.2.4"
authors = [
  { name="Alex Fabre", email="m.alexfabre@gmail.com" },
]
description = "A tool to check git commit messages format"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}

dependencies = [
  "codespell"
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
]

[project.urls]
Homepage = "https://github.com/AlexFabre/commit-format"
Issues = "https://github.com/AlexFabre/commit-format/issues"

[project.scripts]
commit-format = "commit_format.commit_format:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
